CREATE DATABASE IF NOT EXISTS supportticketsdb;
CREATE DATABASE IF NOT EXISTS usersdb;
CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS projectsdb;
CREATE DATABASE IF NOT EXISTS deliverablesdb;
CREATE DATABASE IF NOT EXISTS notificationsdb;
CREATE DATABASE IF NOT EXISTS candidatesdb;